### ISSUE TITLE
Php cant start

### ISSUE THREAD

**Issue by Santy-Gz** [KasRoudra/VidPhisher#1]
![Screenshot_20220624_140123_com termux](https://user-images.githubusercontent.com/69918140/175648826-b46c689c-8d60-42f8-84cd-66bc195f6915.jpg)

I dont know why, i already have instaled php...

Could you help me? Pls

**Comment by KasRoudra** [comment]
@Santy-Gz Run this to check your php 
`php -S 127.0.0.1:8080`

**Comment by Santy-Gz** [comment]
> 

![Uploading Screenshot_20220613_215709_com.google.android.youtube.jpg…]()

**Comment by Santy-Gz** [comment]
> @Santy-Gz Run this to check your php `php -S 127.0.0.1:8080`

**Comment by Santy-Gz** [comment]
![Screenshot_20220625_000615_com termux](https://user-images.githubusercontent.com/69918140/175759152-16f0cbb9-2568-41ed-a35c-da645d37efca.jpg)


I think than it's correct 🤔

**Comment by KasRoudra** [comment]
@Santy-Gz Checking the screenshot, I assume you are missing some necessary folders. Delete the vidphisher files and git clone again
