### ISSUE TITLE
Video problem

### ISSUE THREAD

**Issue by jacoblechu** [KasRoudra/VidPhisher#13]
*I do not know how to send link to others
*But I completed all you have said 
* Please help me

**Comment by KasRoudra** [comment]
@jacoblechu Send in messenger/email/whatsapp/telegram. However, that's not our concern. This written on EDUCATIONAL purposes

**Comment by jacoblechu** [comment]
Please  this is picking only my phone video and I saw it is saved in my library

**Comment by KasRoudra** [comment]
@jacoblechu Then what's the issue?

**Comment by jacoblechu** [comment]
Sorry for the inconvenience 🙏 I just asked this question because I am
trying this for a week . Sorry

**Comment by KasRoudra** [comment]
@jacoblechu There is nothing to be sorry. Questions are welcome. You just have to clearly describe the issue so that we can update it if required
