### ISSUE TITLE
Where are the images in my computer?

### ISSUE THREAD

**Issue by lastttttt** [KasRoudra/VidPhisher#14]
i can't find the images in my computer

**Comment by KasRoudra** [comment]
@lastttttt Your os/distro?

**Comment by lastttttt** [comment]
Win

**Comment by KasRoudra** [comment]
@lastttttt which software WSL/VirtualBox/Docker?

**Comment by lastttttt** [comment]
wdm?

**Comment by lastttttt** [comment]
i use ubuntu for my terminal

**Comment by KasRoudra** [comment]
@lastttttt That's probably wsl. In the terminal you'll find files in $HOME/Documents. Now sharing files between wsl and windows is your concern

**Comment by lastttttt** [comment]
I can't find the documents in my terminal

**Comment by KasRoudra** [comment]
@lastttttt Run `ls $HOME/Documents` and attach screenshot here
