### ISSUE TITLE
Tunneling has failed! Start your own tunneling service at port 8080!

### ISSUE THREAD

**Issue by Saxirdx** [KasRoudra/VidPhisher#2]

**Comment by KasRoudra** [comment]
@Saxirdx If you are using android, turn on hotspot. If it doesn't solve, try using an ngrok account

**Comment by Saxirdx** [comment]
and how do i do that

**Comment by KasRoudra** [comment]
@Saxirdx Check [here](https://github.com/KasRoudra/PyPhisher/issues/1) for ngrok

**Comment by KasRoudra** [comment]
Another tunneler is added. This issue will be more rare
