### ISSUE TITLE
This version Doesn't sent a permission to victim

### ISSUE THREAD

**Issue by DucooA** [KasRoudra/VidPhisher#3]

**Comment by KasRoudra** [comment]
@DucooError Have you tried brave/chrome/opera/firefox?

**Comment by KasRoudra** [comment]
@DucooError I've just checked and found it still asks permission in cloudflared link from brave. Maybe you should retry with another browser or another link

**Comment by jatinsingh42384238** [comment]
How to save received files in gallery ?
