### ISSUE TITLE
I do not receive the files

### ISSUE THREAD

**Issue by TrunksDeDBZ** [KasRoudra/VidPhisher#4]
when I go to the link with my own phone I authorize access to the camera and I do not receive the video

**Comment by KasRoudra** [comment]
@TrunksDeDBZ What happens if you open link in pc and permit camera?

**Comment by TrunksDeDBZ** [comment]
> @TrunksDeDBZ What happens if you open link in pc and permit camera?

I don’t have camera on my pc

**Comment by kalilinuxsippi** [comment]
i dont recive picture and the location is wrog too

**Comment by KasRoudra** [comment]
@kalilinuxsippi What is your browser? The location is the from ip adress. Your ISP controls that
