### ISSUE TITLE
Received files 

### ISSUE THREAD

**Issue by jatinsingh42384238** [KasRoudra/VidPhisher#5]
How to save received files in phone gallery

**Comment by KasRoudra** [comment]
@jatinsingh42384238 Check media folder of Internal storage

**Comment by Mongkol1** [comment]
How can I get the videos

**Comment by KasRoudra** [comment]
@Mongkol1 Give a screenshot of your vidphisher

**Comment by Steexi** [comment]
how can i open the media file? to see the video

**Comment by KasRoudra** [comment]
@Steexi Give a screenshot of your vidphisher

**Comment by Steexi** [comment]
![Screenshot_20220915-015530](https://user-images.githubusercontent.com/99704711/190325683-45c7b2e8-a6c5-4fa0-ba29-49eadc123e4a.jpg)

**Comment by Steexi** [comment]
So what should I do ?

**Comment by KasRoudra** [comment]
@Steexi Check media folder of Internal storage

**Comment by 1wickedwizard1** [comment]
i set the timer for a minute but i dont see any video being saved

**Comment by KasRoudra** [comment]
@1wickedwizard1 Did you set 60000 as the duration? That resembles one minute

**Comment by 1wickedwizard1** [comment]
yes absolutely but i kept waiting for 2 minutes and no video was saved

**Comment by KasRoudra** [comment]
@1wickedwizard1 Did it work when the default timeout was used?
