### ISSUE TITLE
Port forwarding issue

### ISSUE THREAD

**Issue by vaibhavdost** [KasRoudra/VidPhisher#6]
![Screenshot_20220904_165711](https://user-images.githubusercontent.com/61916904/188310957-74299e2f-ff90-496c-b8d6-b076bf696479.jpg)
Same goes for camhacker

**Comment by KasRoudra** [comment]
@vaibhavdost Server is temporarily down. Try again later

**Comment by Duckywe** [comment]
![Screenshot_20221119-043823_Termux.jpg](https://user-images.githubusercontent.com/118424880/202824888-e55ba588-2557-45d3-a6f2-2ae0d44aebee.jpg)

**Comment by Duckywe** [comment]
I have found this issue

**Comment by KasRoudra** [comment]
@Duckywe Your hotspot is turned off

**Comment by Duckywe** [comment]
But bro I use WiFi there is no option for WiFi hotspot there is option for mobile hotspot

**Comment by KasRoudra** [comment]
@Duckywe Turn off wifi. Use cellular data and then turn on mobile hotspot
