### ISSUE TITLE
Cloudflare

### ISSUE THREAD

**Issue by Mikeyxken2** [KasRoudra/VidPhisher#8]
![96D74DCF-9509-47D9-949A-0B81CC3FFE16](https://user-images.githubusercontent.com/117107477/199066993-b875b647-9014-4ad7-9b60-eecece968169.png)
Everytime this error shows, can you help me?

**Comment by KasRoudra** [comment]
@Mikeyxken2 This is a server side error which we've no access to. You may try video option of [maxphisher](https://github.com/KasRoudra/MaxPhisher) and get extra free links

**Comment by Duckywe** [comment]
Sir it shows username is wrong

**Comment by KasRoudra** [comment]
@Duckywe In vidphisher, username is never captured

**Comment by Duckywe** [comment]
What I do know
